# Reusable Security Scan Workflow
#
# A configurable workflow for running security scans using multiple tools.
# Supports selective tool execution and parallel processing for efficiency.
#
# Features:
# - Selective Security Tool Execution
#   • Semgrep: Static Application Security Testing (SAST)
#   • Bandit: Python-specific security linting
#   • Trivy: Container and dependency scanning
#   • ClamAV: Malware detection
#
# Configuration Options:
# - tools: Comma-separated list of tools to run (required)
#   Example: "semgrep,bandit,trivy"
#
# - scan-scope: Scope of the security scan (default: "changed")
#   • "changed": Only scan modified files
#   • "all": Scan entire codebase
#
# - severity-level: Minimum severity to report (default: "LOW")
#   • "LOW": Report all issues
#   • "MEDIUM": Filter out low severity issues
#   • "HIGH": Only report high severity issues
#
# Example Usage:
#   security:
#     uses: ./.github/workflows/_reusable-security-scan.yaml
#     with:
#       tools: "semgrep"
#       scan-scope: "changed"
#       severity-level: "MEDIUM"
#
# Results:
# - Each tool's results are uploaded as workflow artifacts
# - Results are stored in security-results/<tool-name>
# - Artifacts are retained for 7 days

name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      tools:
        description: |
          Security tools to run (comma-separated)
          Valid options: bandit, semgrep, trivy, clamav
        type: string
        required: true
      scan-scope:
        description: "Scan scope (all/changed)"
        type: string
        default: "changed"
      severity-level:
        description: "Minimum severity level (LOW/MEDIUM/HIGH)"
        type: string
        default: "LOW"

jobs:
  security:
    strategy:
      matrix:
        tool: ${{ fromJson('["' + join(split(inputs.tools, ','), '","') + '"]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate security tools
        shell: bash
        run: |
          if [[ ! "${{ matrix.tool }}" =~ ^(bandit|semgrep|trivy|clamav)$ ]]; then
            echo "Error: Invalid security tool specified: ${{ matrix.tool }}"
            echo "Valid tools are: bandit, semgrep, trivy, clamav"
            exit 1
          fi

      - name: Run ${{ matrix.tool }} scan
        uses: ./.github/actions/security/${{ matrix.tool }}
        with:
          scan-scope: ${{ inputs.scan-scope }}
          severity-level: ${{ inputs.severity-level }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.tool }}-results
          path: security-results/${{ matrix.tool }}
          retention-days: 7