# Reusable Release Publisher Workflow
#
# This reusable workflow publishes Python packages to PyPI and creates GitHub releases.
# It supports both production releases and pre-releases to Test PyPI.
#
# Example usage:
#   jobs:
#     publish-release:
#       uses: ./.github/workflows/_reusable-release-publisher.yaml
#       with:
#         version: "1.0.0"
#         artifact-name: "dist-123456789"
#         is-prerelease: false
#       secrets:
#         pypi-token: ${{ secrets.PYPI_TOKEN }}
#         test-pypi-token: ${{ secrets.TEST_PYPI_TOKEN }}

name: Reusable Release Publisher

on:
  workflow_call:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      artifact-name:
        description: "Name of the artifact to publish"
        required: true
        type: string
      is-prerelease:
        description: "Whether this is a pre-release"
        type: boolean
        default: false
    secrets:
      pypi-token:
        required: true
        description: "PyPI token for package publishing"
      test-pypi-token:
        required: false
        description: "Test PyPI token for pre-releases"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.is-prerelease && 'staging' || 'production' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.is-prerelease && secrets.test-pypi-token || secrets.pypi-token }}
          TWINE_REPOSITORY_URL: ${{ inputs.is-prerelease && 'https://test.pypi.org/legacy/' || '' }}
        run: |
          pip install --upgrade pip twine
          twine upload dist/*
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: ${{ inputs.is-prerelease }}
          files: dist/*
          generate_release_notes: true
