name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      tools:
        description: "Security tools to run (comma-separated: bandit,clamav,semgrep,trivy)"
        type: string
        default: "bandit,semgrep"
      scan-scope:
        description: "Scan scope (all/changed)"
        type: string
        default: "changed"
      severity-level:
        description: "Minimum severity level (LOW/MEDIUM/HIGH)"
        type: string
        default: "LOW"
      fail-on-findings:
        description: "Fail workflow if issues found"
        type: boolean
        default: true
    outputs:
      has-findings:
        description: "Whether any security issues were found"
        value: ${{ jobs.summarize.outputs.has_findings }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tools-array: ${{ steps.parse-tools.outputs.tools_json }}
    steps:
      - id: parse-tools
        run: |
          TOOLS="${{ inputs.tools }}"
          if [[ "$TOOLS" == "all" ]]; then
            TOOLS="bandit,clamav,semgrep,trivy"
          fi
          # Convert comma-separated string to JSON array
          JSON_ARRAY=$(echo "$TOOLS" | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "tools_json=$JSON_ARRAY" >> $GITHUB_OUTPUT

  run-scans:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: ${{ fromJSON(needs.setup.outputs.tools-array) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ${{ matrix.tool }} scan
        uses: ./.github/actions/security/${{ matrix.tool }}
        with:
          scan-scope: ${{ inputs.scan-scope }}
          severity-level: ${{ inputs.severity-level }}
          fail-on-findings: ${{ inputs.fail-on-findings }}

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tool }}-results
          path: security-results/${{ matrix.tool }}
          retention-days: 7

  summarize:
    needs: run-scans
    runs-on: ubuntu-latest
    outputs:
      has_findings: ${{ steps.check-findings.outputs.has_findings }}
    steps:
      - id: check-findings
        run: |
          if [[ "${{ contains(needs.run-scans.result, 'failure') }}" == "true" ]]; then
            echo "has_findings=true" >> $GITHUB_OUTPUT
          else
            echo "has_findings=false" >> $GITHUB_OUTPUT
          fi