name: Production Release Process

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      pypi-token:
        required: true

jobs:
  validate-release-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approved RC
        run: |
          VERSION="${{ inputs.version }}"
          ARTIFACTS_JSON=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/artifacts")

          RC_APPROVAL=$(echo "$ARTIFACTS_JSON" | jq -r --arg ver "${VERSION%-*}" \
            '.artifacts[] | select(.name | startswith("rc-approval-v" + $ver))')

          if [ -z "$RC_APPROVAL" ]; then
            echo "::error::No approved RC found for version $VERSION"
            exit 1
          fi

  prepare-release:
    needs: [validate-release-readiness]
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist

      - name: Upload for production release
        uses: actions/upload-artifact@v4
        with:
          name: production-release-artifacts
          path: dist/
          retention-days: 1

  publish:
    needs: [prepare-release]
    uses: ./.github/workflows/_reusable-release-publisher.yaml
    with:
      version: ${{ inputs.version }}
      artifact-name: production-release-artifacts
      is-prerelease: false
    secrets:
      pypi-token: ${{ secrets.pypi-token }}
