# Reusable Code Quality Workflow
#
# This reusable workflow runs various code quality checks using
# pre-commit hooks and other quality assurance tools.
#
# Features:
# - Pre-commit hook execution
# - Multiple language support
# - Configurable environments
# - Caching for performance
#
# Quality Checks:
# - Linting
# - Formatting
# - Type checking
# - Style enforcement
#
# Example Usage:
#   jobs:
#     quality:
#       uses: ./.github/workflows/_reusable-code-quality.yaml
#       with:
#         python-version: "3.11"
#         node-version: "20.0.0"
#
# Note: Requires configured pre-commit hooks in repository

name: Reusable Code Quality

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version for checks"
        type: string
        default: "3.10"
      node-version:
        description: "Node.js version for checks"
        type: string
        default: "18.15.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/code-quality/pre-commit
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ inputs.node-version }}
