name: Reusable Code Quality

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version for checks"
        type: string
        default: "3.10"
      node-version:
        description: "Node.js version for checks"
        type: string
        default: "18.15.0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/code-quality/pre-commit
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ inputs.node-version }}
