# Reusable Security Scan Workflow
#
# This reusable workflow orchestrates multiple security scanning tools to provide
# comprehensive security analysis of the codebase. It integrates various specialized
# scanners for different security aspects.
#
# Features:
# - Multi-tool Security Analysis
#   • Bandit for Python security
#   • ClamAV for malware detection
#   • Semgrep for SAST
#   • Trivy for vulnerabilities
#
# Scanning Capabilities:
# - Code security analysis
# - Dependency vulnerability checks
# - Infrastructure as Code scanning
# - Malware detection
# - Secret detection
# - Container security
#
# Execution Modes:
# - Full repository scan
# - Changed files only
# - Configurable tool selection
# - Adjustable severity levels
#
# Performance Features:
# - Parallel tool execution
# - Scan result caching
# - Incremental scanning
# - Resource optimization
#
# Example Usage:
#   jobs:
#     security:
#       uses: ./.github/workflows/_reusable-security-scan.yaml
#       with:
#         tools: "bandit,semgrep,trivy"
#         scan-scope: "changed"
#         severity-level: "MEDIUM"
#
# Note: Different security tools may require specific permissions
# or configurations. Results are preserved as workflow artifacts.

name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      tools:
        description: |
          Security tools to run (comma-separated)
          Valid options: bandit, semgrep, trivy, clamav
        type: string
        required: true
      scan-scope:
        description: "Scan scope (all/changed)"
        type: string
        default: "changed"
      severity-level:
        description: "Minimum severity level (LOW/MEDIUM/HIGH)"
        type: string
        default: "LOW"

jobs:
  security:
    strategy:
      matrix:
        tool:
          - bandit
          - semgrep
          - trivy
          - clamav
        exclude:
          - tool: bandit
            ${{ !contains(inputs.tools, 'bandit') }}
          - tool: semgrep
            ${{ !contains(inputs.tools, 'semgrep') }}
          - tool: trivy
            ${{ !contains(inputs.tools, 'trivy') }}
          - tool: clamav
            ${{ !contains(inputs.tools, 'clamav') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate security tools
        uses: ./.github/actions/security/validate-tools
        with:
          tools: ${{ inputs.tools }}

      - name: Run ${{ matrix.tool }} scan
        uses: ./.github/actions/security/${{ matrix.tool }}
        with:
          scan-scope: ${{ inputs.scan-scope }}
          severity-level: ${{ inputs.severity-level }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.tool }}-results
          path: security-results/${{ matrix.tool }}
          retention-days: 7