name: Reusable Version Check

on:
  workflow_call:
    inputs:
      version:
        description: "Version to validate"
        required: false
        type: string
      allow-prerelease:
        description: "Allow pre-release versions"
        type: boolean
        default: true
    outputs:
      version:
        description: "Validated version"
        value: ${{ jobs.validate.outputs.version }}
      is_prerelease:
        description: "Whether version is a pre-release"
        value: ${{ jobs.validate.outputs.is_prerelease }}

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is_prerelease: ${{ steps.check-prerelease.outputs.is_prerelease }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate version
        id: get-version
        run: |
          VERSION="${{ inputs.version || github.ref_name }}"
          if ! [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$ ]]; then
            echo "::error::Invalid version format. Must be vX.Y.Z or vX.Y.Z-rcN"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Check pre-release
        id: check-prerelease
        run: |
          if [[ "${{ steps.get-version.outputs.version }}" =~ -rc[0-9]+$ ]]; then
            if [[ "${{ inputs.allow-prerelease }}" != "true" ]]; then
              echo "::error::Pre-release versions are not allowed"
              exit 1
            fi
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
