name: PR Checks

on:
  pull_request:
    branches: [main, "feature/**"]
    paths-ignore: ["docs/**", "*.md", "LICENSE"]

jobs:
  quality:
    uses: ./.github/workflows/_reusable-code-quality.yaml
    with:
      python-version: "3.10"
      node-version: "18.15.0"

  tests:
    uses: ./.github/workflows/_reusable-test-suite.yaml
    with:
      test-types: "unit,integration"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  security:
    needs: [quality]
    uses: ./.github/workflows/_reusable-security-scan.yaml
    with:
      tools: "bandit,semgrep"
      scan-scope: "changed"
      severity-level: "MEDIUM"
