# Pull Request Checks Workflow
#
# This workflow runs various checks on pull requests including:
# - Code quality checks (linting, style, type checking)
# - Test suite (unit and integration tests)
# - Security scans (bandit and semgrep)
#
# Triggers:
# - On pull requests to main branch
# - On pull requests to feature/* branches
#
# Uses reusable workflows for:
# - Code quality (./.github/workflows/_reusable-code-quality.yaml)
# - Test suite (./.github/workflows/_reusable-test-suite.yaml)
# - Security scanning (./.github/workflows/_reusable-security-scan.yaml)

name: PR Checks

on:
  pull_request:
    branches: [main, "feature/**"]

jobs:
  quality:
    uses: ./.github/workflows/_reusable-code-quality.yaml
    with:
      python-version: "3.10"
      node-version: "18.15.0"

  tests:
    uses: ./.github/workflows/_reusable-test-suite.yaml
    with:
      test-types: "unit,integration"
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  security:
    needs: [quality]
    uses: ./.github/workflows/_reusable-security-scan.yaml
    with:
      tools: "bandit,semgrep"
      scan-scope: "changed"
      severity-level: "MEDIUM"
